version: '3'

services:
  mongodb:
    image: mongo:4.2
    container_name: mongo_container
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    hostname: nosql
